repos:
- repo: https://github.com/psf/black
  rev: 23.12.1 # Replace by any tag/version: https://github.com/psf/black/tags
  hooks:
  - id: black
    language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: flake8
    - id: end-of-file-fixer
# -   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.780
#    hooks:
#    -   id: mypy
#        args: [--config-file=.mypy.ini, resy_bot]
#        exclude: tests
